

development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: renukarajan
  password: secret

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: renukarajan
  password: secret



